site_name: Modern XMPP

nav:
  - 'Home': 'index.md'
  - 'Guidelines':
    - 'Overview': client-guidelines/index.md
    - 'Protocol': client-guidelines/protocol.md
    - 'Multi-user Chats': client-guidelines/groupchat.md
  - 'Terminology': terminology.md

markdown_extensions:
    - admonition
    - def_list
    - footnotes
