site_name: Modern XMPP

nav:
  - 'Home': 'index.md'
  - 'Guidelines':
    - 'User Interface': client/design.md
    - 'Protocol': client/protocol.md
    - 'Multi-user Chats': client/groupchat.md
  - 'Terminology': terminology.md

markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - toc:
      permalink: true

site_url: https://docs.modernxmpp.org/
repo_url: https://github.com/modernxmpp/modernxmpp
edit_uri: edit/draft/docs

extra_css:
  - 'css/modernxmpp.css'
